name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main # Adjust to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t server .

      - name: Tag Docker image
        run: docker tag server ${{ secrets.DOCKER_USERNAME }}/server

      - name: Log in to Docker Hub (or your registry)
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/server

      - name: Stop Previous Docker image
        run: docker stop $(docker ps -a -q)
        
      - name: SSH into remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull  ${{ secrets.DOCKER_USERNAME }}/server
            docker run -d -p 1212:1212 ${{ secrets.DOCKER_USERNAME }}/server